name: jabu_test_bloc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.4.1
  graphql_flutter: ^5.1.2
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  path_provider: ^2.0.15
  random_name_generator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0 # flutter pub run change_app_package_name:main mx.com.waddi.testapp
  flutter_launcher_icons: ^0.12.0 # flutter pub run flutter_launcher_icons
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  isar_generator: 3.1.0
  mockito: ^5.4.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true
