name: jabu_test
description: Jabu Test.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.4.1
  graphql_flutter: ^5.1.2
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  path_provider: ^2.0.15
  uikit:  
    path: packages/uikit

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  change_app_package_name: ^1.1.0 # flutter pub run change_app_package_name:main py.com.jabu.flutter_test
  flutter_launcher_icons: ^0.12.0 # flutter pub run flutter_launcher_icons
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^0.13.0
  isar_generator: 3.1.0
  mockito: ^5.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptative_icon_background: "assets/images/logo.jpg"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/

  uses-material-design: true
